name: hugo publish

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: macOS 10.15.6
    steps:
    - uses: actions/checkout@master
      # with:
      #   submodules: true

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2.2.0
      with:
        hugo-version: '0.70.0'
        extended: true

    - name: Build
      run: hugo --minify --cleanDestinationDir

    - name: Deploy
      uses: w9jds/firebase-action@master
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        EXTERNAL_REPOSITORY: XushengLuo/XushengLuo.github.io
        PUBLISH_BRANCH: master
        PUBLISH_DIR: ./public
      with:
        emptyCommits: false
        commitMessage: ${{ github.event.head_commit.message }}
